services:
  nat-link-server:
    build: .
    restart: unless-stopped
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002/udp"
      - "7003:7003/udp"
      - "8080:8080"
    volumes:
      - nat-link-data:/opt/nat-link/data
      - nat-link-logs:/opt/nat-link/logs
      - ./config.docker.yaml:/opt/nat-link/config.yaml:ro
      - ./tls:/opt/nat-link/tls:ro

volumes:
  nat-link-data:
  nat-link-logs:
