// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Tunnel {
    "id": string;
    "client_id": string;
    "name": string;
    "protocol": string;
    "local_host": string;
    "local_port": number;
    "remote_port": number;
    "domain": string;
    "status": string;
    "ip_allowlist": string[] | null;
    "created_at": string;
    "updated_at": string;
}
