// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckForUpdate(): $CancellablePromise<$models.UpdateResult> {
    return $Call.ByID(1073638667);
}

export function Connect(): $CancellablePromise<$models.RuntimeStatus> {
    return $Call.ByID(761302137);
}

export function Disconnect(): $CancellablePromise<$models.RuntimeStatus> {
    return $Call.ByID(3778713963);
}

export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(2947540501);
}

export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3613445466, url);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(1821349302);
}

export function SaveConfig(patch: $models.AppConfigPatch): $CancellablePromise<$models.DesktopSnapshot> {
    return $Call.ByID(2379168358, patch);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(872464160);
}

export function Snapshot(): $CancellablePromise<$models.DesktopSnapshot> {
    return $Call.ByID(431882765);
}

export function Status(): $CancellablePromise<$models.RuntimeStatus> {
    return $Call.ByID(3733088879);
}
