// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../internal/model/models.js";

export interface AppConfig {
    "serverUrl": string;
    "dataAddress": string;
    "transport": string;
    "quicAddress": string;
    "caFile": string;
    "token": string;
    "name": string;
    "deviceId": string;
    "insecureSkipVerify": boolean;
    "autoStart": boolean;
}

export interface AppConfigPatch {
    "serverUrl": string | null;
    "dataAddress": string | null;
    "transport": string | null;
    "quicAddress": string | null;
    "caFile": string | null;
    "token": string | null;
    "name": string | null;
    "deviceId": string | null;
    "insecureSkipVerify": boolean | null;
    "autoStart": boolean | null;
}

export interface DesktopSnapshot {
    "config": AppConfig;
    "status": RuntimeStatus;
    "tunnels": model$0.Tunnel[] | null;
    "tunnelPaths": { [_ in string]?: string } | null;
    "logs": LogEntry[] | null;
    "update"?: UpdateResult;
}

export interface LogEntry {
    "time": string;
    "level": string;
    "message": string;
    "fields": { [_ in string]?: any } | null;
}

export interface RuntimeStatus {
    "connected": boolean;
    "state": string;
    "message": string;
    "version": string;
    "uploadBytes": number;
    "downloadBytes": number;
    "lastStartedAt"?: string;
    "lastStoppedAt"?: string;
}

export interface UpdateResult {
    "checked": boolean;
    "available": boolean;
    "latestVersion": string;
    "downloadURL": string;
    "message": string;
}
